In [53]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import datetime as dt
import plotly.express as px

In [54]:
try:
    df_assessment: pd.DataFrame = pd.read_csv(
        "data/assessments_G5P3.csv",
    )
    # df_delivery: pd.DataFrame = pd.read_csv("dummy_stuff/dummy_delivery.csv")
    # df_logs: pd.DataFrame = pd.read_csv("dummy_stuff/dummy_logs.csv")
except FileNotFoundError as e:
    raise FileNotFoundError(f"Error: {e}. Please ensure the CSV files are in the correct directory.")
except pd.errors.EmptyDataError as e:
    raise ValueError(f"Error: {e}. The CSV files are empty. Please provide valid data.")

df_assessment.head()

,assessment_code,assessment_name,module_code,module_name,date_released,date_due,recommended_hours,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11
0,ZDAT1001_13102025,Portfolio 1,ZDAT1001,Software Portfolio Assessment,13-Oct-25,19-Nov-25,20.0,NaN,NaN,NaN,NaN,NaN
1,ZDAT1001_15012026,Portfolio 2,ZDAT1001,Software Portfolio Assessment,15-Jan-26,22-Apr-26,35.0,NaN,NaN,NaN,NaN,NaN
2,ZDAT1001_21042026,Portfolio 3,ZDAT1001,Software Portfolio Assessment,21-Apr-26,17-Jun-26,45.0,NaN,NaN,NaN,NaN,NaN
3,ZDAT1002_07012026,Assignment 1 ? Data Science Pipeline Report,ZDAT1002,Fundamental Skills Assessment,07-Jan-26,18-Feb-26,12.0,NaN,NaN,NaN,NaN,NaN
4,ZDAT1002_08022026,Assignment 2 ? Maths Portfolio,ZDAT1002,Fundamental Skills Assessment,08-Feb-26,09-Jun-26,15.0,NaN,NaN,NaN,NaN,NaN

In [55]:
# clean date columns in df_assessment
df_assessment['date_released'] = pd.to_datetime(df_assessment['date_released'], format="%d-%b-%y", errors='coerce')
df_assessment['date_due'] = pd.to_datetime(df_assessment['date_due'], format="%d-%b-%y", errors='coerce')
df_assessment["category"] = df_assessment["recommended_hours"].apply(
    lambda x: "High" if x > 7.4 else ("Medium" if x > 4 else "Low")
)

In [56]:
df_assessment.head()

,assessment_code,assessment_name,module_code,module_name,date_released,date_due,recommended_hours,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,category
0,ZDAT1001_13102025,Portfolio 1,ZDAT1001,Software Portfolio Assessment,2025-10-13,2025-11-19,20.0,NaN,NaN,NaN,NaN,NaN,High
1,ZDAT1001_15012026,Portfolio 2,ZDAT1001,Software Portfolio Assessment,2026-01-15,2026-04-22,35.0,NaN,NaN,NaN,NaN,NaN,High
2,ZDAT1001_21042026,Portfolio 3,ZDAT1001,Software Portfolio Assessment,2026-04-21,2026-06-17,45.0,NaN,NaN,NaN,NaN,NaN,High
3,ZDAT1002_07012026,Assignment 1 ? Data Science Pipeline Report,ZDAT1002,Fundamental Skills Assessment,2026-01-07,2026-02-18,12.0,NaN,NaN,NaN,NaN,NaN,High
4,ZDAT1002_08022026,Assignment 2 ? Maths Portfolio,ZDAT1002,Fundamental Skills Assessment,2026-02-08,2026-06-09,15.0,NaN,NaN,NaN,NaN,NaN,High

In [57]:
# filter to only include rows which include time taken in assessment
fig = px.timeline(
    df_assessment,
    x_start="date_released",
    x_end="date_due",
    color="category",
    hover_name="module_code",
    color_discrete_map={"Low": "#66bb6a", "Medium": "#ffca28", "High": "#ef5350"},
)

fig.update_yaxes(autorange="reversed")

fig.update_layout(
    title="Apprenticeship Timeline",
    xaxis_title="Date",
    yaxis_title="Activity",
    height=450,
)

fig.show()