In [19]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import datetime as dt
import plotly.express as px

In [20]:
try:
    df_assessment: pd.DataFrame = pd.read_csv("dummy_stuff/dummy_assess.csv", )
    # df_delivery: pd.DataFrame = pd.read_csv("dummy_stuff/dummy_delivery.csv")
    # df_logs: pd.DataFrame = pd.read_csv("dummy_stuff/dummy_logs.csv")
except FileNotFoundError as e:
    raise FileNotFoundError(f"Error: {e}. Please ensure the CSV files are in the correct directory.")
except pd.errors.EmptyDataError as e:
    raise ValueError(f"Error: {e}. The CSV files are empty. Please provide valid data.")

df_assessment.head()

,assessment_code,assessment_name,module_code,module_name,date_released,date_due,recommended_hours
0,ZDAT1001,TEST_ASSESS,DATA1001,TEST,06/05/2026,06/06/2026,20
1,ZDAT1002,TEST_ASSESS,DATA1002,TEST,06/04/2026,06/06/2026,30
2,ZDAT1003,TEST_ASSESS,DATA1003,TEST,06/03/2026,06/06/2026,10
3,ZDAT1004,TEST_ASSESS,DATA1004,TEST,06/02/2026,06/06/2026,5
4,ZDAT1005,TEST_ASSESS,DATA1005,TEST,06/01/2026,06/06/2026,2

In [21]:
# clean date columns in df_assessment
df_assessment['date_released'] = pd.to_datetime(df_assessment['date_released'], format='%d/%m/%Y', errors='coerce')
df_assessment['date_due'] = pd.to_datetime(df_assessment['date_due'], format='%d/%m/%Y', errors='coerce')
df_assessment["category"] = df_assessment["recommended_hours"].apply(
    lambda x: "High" if x > 7.4 else ("Medium" if x > 4 else "Low")
)

In [22]:
df_assessment.head()

,assessment_code,assessment_name,module_code,module_name,date_released,date_due,recommended_hours,category
0,ZDAT1001,TEST_ASSESS,DATA1001,TEST,2026-05-06,2026-06-06,20,High
1,ZDAT1002,TEST_ASSESS,DATA1002,TEST,2026-04-06,2026-06-06,30,High
2,ZDAT1003,TEST_ASSESS,DATA1003,TEST,2026-03-06,2026-06-06,10,High
3,ZDAT1004,TEST_ASSESS,DATA1004,TEST,2026-02-06,2026-06-06,5,Medium
4,ZDAT1005,TEST_ASSESS,DATA1005,TEST,2026-01-06,2026-06-06,2,Low

In [25]:
# filter to only include rows which include time taken in assessment
fig = px.timeline(
    df_assessment,
    x_start="date_released",
    x_end="date_due",
    y="module_code",
    color="category",
    hover_name="module_code",
    color_discrete_map={"Low": "#66bb6a", "Medium": "#ffca28", "High": "#ef5350"},
)

fig.update_yaxes(autorange="reversed")

fig.update_layout(
    title="Apprenticeship Timeline",
    xaxis_title="Date",
    yaxis_title="Activity",
    height=450,
)

fig.show()